import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  appSidebar: [
    {
      type: 'category',
      label: 'ガイド & マニュアル',
      link: {
        type: 'generated-index',
        slug: '/', 
        title: 'ガイド & マニュアル',
        description: 'アプリ全体の目次（TOC）です。各章に進むには以下のカードを選択してください。',
      },
      items: [{ type: 'autogenerated', dirName: '.' }],
      collapsed: false,
    },
  ],
};

export default sidebars;